# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/guo/Desktop/test

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/guo/Desktop/test

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/guo/Desktop/test/CMakeFiles /home/guo/Desktop/test/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/guo/Desktop/test/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Inst

# Build rule for target.
Inst: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Inst
.PHONY : Inst

# fast build rule for target.
Inst/fast:
	$(MAKE) -f CMakeFiles/Inst.dir/build.make CMakeFiles/Inst.dir/build
.PHONY : Inst/fast

#=============================================================================
# Target rules for targets named codeCoverage

# Build rule for target.
codeCoverage: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 codeCoverage
.PHONY : codeCoverage

# fast build rule for target.
codeCoverage/fast:
	$(MAKE) -f CMakeFiles/codeCoverage.dir/build.make CMakeFiles/codeCoverage.dir/build
.PHONY : codeCoverage/fast

#=============================================================================
# Target rules for targets named demo

# Build rule for target.
demo: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 demo
.PHONY : demo

# fast build rule for target.
demo/fast:
	$(MAKE) -f CMakeFiles/demo.dir/build.make CMakeFiles/demo.dir/build
.PHONY : demo/fast

codeCoverage.o: codeCoverage.cpp.o

.PHONY : codeCoverage.o

# target to build an object file
codeCoverage.cpp.o:
	$(MAKE) -f CMakeFiles/codeCoverage.dir/build.make CMakeFiles/codeCoverage.dir/codeCoverage.cpp.o
.PHONY : codeCoverage.cpp.o

codeCoverage.i: codeCoverage.cpp.i

.PHONY : codeCoverage.i

# target to preprocess a source file
codeCoverage.cpp.i:
	$(MAKE) -f CMakeFiles/codeCoverage.dir/build.make CMakeFiles/codeCoverage.dir/codeCoverage.cpp.i
.PHONY : codeCoverage.cpp.i

codeCoverage.s: codeCoverage.cpp.s

.PHONY : codeCoverage.s

# target to generate assembly for a file
codeCoverage.cpp.s:
	$(MAKE) -f CMakeFiles/codeCoverage.dir/build.make CMakeFiles/codeCoverage.dir/codeCoverage.cpp.s
.PHONY : codeCoverage.cpp.s

demo.o: demo.cpp.o

.PHONY : demo.o

# target to build an object file
demo.cpp.o:
	$(MAKE) -f CMakeFiles/demo.dir/build.make CMakeFiles/demo.dir/demo.cpp.o
.PHONY : demo.cpp.o

demo.i: demo.cpp.i

.PHONY : demo.i

# target to preprocess a source file
demo.cpp.i:
	$(MAKE) -f CMakeFiles/demo.dir/build.make CMakeFiles/demo.dir/demo.cpp.i
.PHONY : demo.cpp.i

demo.s: demo.cpp.s

.PHONY : demo.s

# target to generate assembly for a file
demo.cpp.s:
	$(MAKE) -f CMakeFiles/demo.dir/build.make CMakeFiles/demo.dir/demo.cpp.s
.PHONY : demo.cpp.s

libInst.o: libInst.cpp.o

.PHONY : libInst.o

# target to build an object file
libInst.cpp.o:
	$(MAKE) -f CMakeFiles/Inst.dir/build.make CMakeFiles/Inst.dir/libInst.cpp.o
.PHONY : libInst.cpp.o

libInst.i: libInst.cpp.i

.PHONY : libInst.i

# target to preprocess a source file
libInst.cpp.i:
	$(MAKE) -f CMakeFiles/Inst.dir/build.make CMakeFiles/Inst.dir/libInst.cpp.i
.PHONY : libInst.cpp.i

libInst.s: libInst.cpp.s

.PHONY : libInst.s

# target to generate assembly for a file
libInst.cpp.s:
	$(MAKE) -f CMakeFiles/Inst.dir/build.make CMakeFiles/Inst.dir/libInst.cpp.s
.PHONY : libInst.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... Inst"
	@echo "... codeCoverage"
	@echo "... demo"
	@echo "... rebuild_cache"
	@echo "... codeCoverage.o"
	@echo "... codeCoverage.i"
	@echo "... codeCoverage.s"
	@echo "... demo.o"
	@echo "... demo.i"
	@echo "... demo.s"
	@echo "... libInst.o"
	@echo "... libInst.i"
	@echo "... libInst.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

